### ISSUE TITLE
Edit Content no preview image 

### ISSUE THREAD

**Issue by Dhy19971** [jr-k/obscreen#104]
When you go to Edit Content, in my case for an image, the preview is not displayed correctly.

![Screenshot 2024-07-17 091014](https://github.com/user-attachments/assets/ba06b34f-5a97-4ad9-88b3-4d228903dcb8)

**Sofware (please complete the following information):**
 - *Obscreen version*: `v2.00`
 - *Installation method*:  `System`

**Comment by jr-k** [comment]
@Dhy19971 send me the file please

**Comment by Dhy19971** [comment]
A common JPEG/PNG. 
The same thing also happens for YouTube video content.

**Comment by Dhy19971** [comment]
Like this
![png-clipart-minions-minions](https://github.com/user-attachments/assets/a0af6592-8982-4a51-a147-bb735854f93b)

**Comment by jr-k** [comment]
I can't reproduce this behaviour.
<img width="1724" alt="Capture d’écran 2024-07-17 à 12 13 51" src="https://github.com/user-attachments/assets/5c5b2848-bda5-4075-901f-0968d2655387">

**Comment by Dhy19971** [comment]
Everything ok. It was a problem with my reverse proxy. Thank you.
