### ISSUE TITLE
Obscreen documentation

### ISSUE THREAD

**Issue by Dhy19971** [jr-k/obscreen#110]
I tried to orient myself in your project but without success. It would be very useful a documentation that can explain the structure of the project and the tools you are using. It would be very useful to possibly be able to contribute.

**Comment by Dhy19971** [comment]
A complete description of the case use of the program. And something that explains the structure of the program itself in terms of architecture would also be very useful.

**Comment by Dhy19971** [comment]
I think it could be very useful to have comments that briefly explain the code and functions. This is to be able to avoid interpretations and misunderstandings in reading the code.

**Comment by jr-k** [comment]
The quality of the code is not the highest I can deliver. 

Priority was given to functionality and rapid prototyping of features missing in other tools. The project is still very young, and it's more in the alpha phase than a mature project with processes, complete documentation, etc. 

It’s not very useful to document code that will likely change quickly if obscreen is to become more secure in the future.

But there is a good foundation to build something nice :)

I'm closing this issue as I don't really need an issue to write documentation but be sure that it'll be a point to expand on sooner or later.
