### ISSUE TITLE
add API

### ISSUE THREAD

**Issue by GrLinkDn** [jr-k/obscreen#113]
Hello and congratulations for your project!!

I think it could be very useful to be able to use APIs to make requests of this type from other programs:

- Create a new playlist

- Add previously uploaded content to a playlist

- Activate or deactivate a playlist or an item contained in it

An API of this type would make your project truly limitless as it can be easily integrated with other contexts and use cases that may not be foreseen and that you don't want to implement.

**Comment by Dhy19971** [comment]
Good idea, it would solve some problems I have.

**Comment by jr-k** [comment]
Yeah, it's in my todo since weeks.

**Comment by pwiepatrick** [comment]
First and foremost, thank you very much for the fantastic project. The API would be really great for me. I need a specific asset for a particular case, and this could be realized with the API.

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v2.3.0
