### ISSUE TITLE
Chromecast and similar device

### ISSUE THREAD

**Issue by GrLinkDn** [jr-k/obscreen#118]
In your opinion, would it be possible to use obscreen to send the slider to a Chromecast or equivalent device?

**Comment by jr-k** [comment]
@GrLinkDn, you can use [this Chromecast Dashboard sender](https://boombatower.github.io/chromecast-dashboard/sender/).

Please ensure that your URL uses HTTPS. You can test it with https://demo.obscreen.io, which works well with Chromecast (I just tested it).

**Comment by GrLinkDn** [comment]
Is no possible to integrate in Obscreen directly ?

**Comment by jr-k** [comment]
Everything is possible, but it's not in the roadmap yet

**Comment by GrLinkDn** [comment]
I realize you said not to be on the agenda. 

I took the liberty of writing a very simple function that looks for a Chromecast device with a certain name and forces it to play a given web address. In my case an obscreen slider.

I checked the dependency and it appears to be extremely supported and reliable being "affiliated" with hassio and therefore with the Open Home Foundation.

It could be used to add a simple button to the playlist that opens a field where you can enter the name of the Chromecast device to play it on.

I was wondering if a small exception could be made since the basic implementation is very simple.

```
    import time
    import pychromecast
    from pychromecast.controllers import dashcast
    def chromecast_search(name, link):

        print(name)
        print(link)


        chromecasts, browser = pychromecast.get_listed_chromecasts(friendly_names=[name])


        print([cc.device.friendly_name for cc in chromecasts])

        try:
            
            cast = chromecasts[0]
            cast.wait()

            dash = dashcast.DashCastController()
            cast.register_handler(dash)

            for count in range(2):

                time.sleep(3)
                dash.load_url(link, True)            
        
        except:
            print("Chromecast not found")
```

**Comment by jr-k** [comment]
any PR is welcome

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v2.3.1 @GrLinkDn

**Comment by GrLinkDn** [comment]
I updated my docker instance as I have done many times before. I get this error again. 

It also tells you that your demo site is giving a 404 error

```
Traceback (most recent call last):
  File "/app/obscreen.py", line 4, in <module>
    from src.Application import Application
  File "/app/src/Application.py", line 7, in <module>
    from src.service.PluginStore import PluginStore
  File "/app/src/service/PluginStore.py", line 12, in <module>
    from src.service.WebServer import WebServer
  File "/app/src/service/WebServer.py", line 22, in <module>
    from src.controller.CoreController import CoreController
  File "/app/src/controller/CoreController.py", line 5, in <module>
    from src.util.UtilChromecast import fetch_friendly_names, cast_url
ImportError: cannot import name 'fetch_friendly_names' from 'src.util.UtilChromecast' (/app/src/util/UtilChromecast.py)
```

**Comment by jr-k** [comment]
Oops... Can you try again please ?

**Comment by GrLinkDn** [comment]
Forgive me but I don't understand how it should work.

I saw the new button near the preview but it is brown and if I click it it doesn't work. 

Am I doing something wrong?

Ver docker composed.

**Comment by GrLinkDn** [comment]
![Screenshot 2024-08-07 192419](https://github.com/user-attachments/assets/82f9e202-430b-4a53-b4b2-023e43f19929)

**Comment by jr-k** [comment]
@GrLinkDn can you keep going on discord ? It'll be easier for me to assist you.
