### ISSUE TITLE
Weekly Slide programming

### ISSUE THREAD

**Issue by Dhy19971** [jr-k/obscreen#119]
I created a playlist as follows:

- two slides in permanent loops
- 2 slides have been scheduled for each day of the week

The first slide is scheduled to join the loop from 11.30 to 14.30. The second from 18.30 to 22.00.

They are different image files for each day and time. All in standard PNG format.

The problem lies in the fact that in no case has the slide started in a loop regardless of the day or time. Same situation for interruption. If you start a slide manually and then schedule the interruption, it will not work.

I also noticed that the timer that calculates the time of total reproduction indicated, in the last case mentioned, an error. It was not considered the time of the slide, which was to be according to the tabuling deactivates, but which in fact was always in a loop.

Can it be a problem due to the docker?

**Sofware:**
 - *Obscreen version*: `v2.1.1`
 - *Installation method*: `Docker`
 - *Browser*: `Chrome`

**Comment by jr-k** [comment]
Send me a backup of your data to help speed up the debugging process. Please ensure that no sensitive data is included in your slides and follow these steps:
```bash
cd obscreen
tar -vcf data.tar data/
```

**Comment by Dhy19971** [comment]
I found a profound difference between the wide and the Docker installation. In Docker, weekly scheduling, in my case, does not work correctly or predictably.  The wide version is currently doing well.

**Comment by Dhy19971** [comment]
I use docker compose.

**Comment by jr-k** [comment]
@Dhy19971 is it ok with https://github.com/jr-k/obscreen/releases/tag/v2.2.3 ?
