### ISSUE TITLE
How can i add new feature in navbar

### ISSUE THREAD

**Issue by AdakHaddad** [jr-k/obscreen#120]
I want to add new dashboard page in the bottom of 'Settings' navigation. Is it  necessary using a framework first?

Because i added each similar variable on many file and just make it error

obscreen  | ERROR:src.service.WebServer:Exception on /playlist/list/0 [GET]
obscreen  | Traceback (most recent call last):
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
obscreen  |     response = self.full_dispatch_request()
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
obscreen  |     rv = self.handle_user_exception(e)
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
obscreen  |     rv = self.dispatch_request()
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
obscreen  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
obscreen  |   File "/app/src/service/WebServer.py", line 93, in decorated_function
obscreen  |     return f(*args, **kwargs)
obscreen  |   File "/app/src/controller/PlaylistController.py", line 36, in playlist_list
obscreen  |     return render_template(
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
obscreen  |     return _render(app, template, context)
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
obscreen  |     rv = template.render(context)
obscreen  |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
obscreen  |     self.environment.handle_exception()
obscreen  |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
obscreen  |     raise rewrite_traceback_stack(source=source)
obscreen  |   File "/app/views/playlist/list.jinja.html", line 1, in top-level template code
obscreen  |     {% extends 'base.jinja.html' %}
obscreen  |   File "/app/views/base.jinja.html", line 137, in top-level template code
obscreen  |     {% block header %}
obscreen  |   File "/app/views/base.jinja.html", line 153, in block 'header'
obscreen  |     <a href="{{ url_for(menu.main_pill_route) }}">
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1697, in url_for
obscreen  |     return self.handle_url_build_error(error, endpoint, values)
obscreen  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1686, in url_for
obscreen  |     rv = url_adapter.build(  # type: ignore[union-attr]
obscreen  |   File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
obscreen  |     raise BuildError(endpoint, values, method, self)
obscreen  | werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard_index'. Did you mean 'player_default' instead?

**Comment by jr-k** [comment]
Best approch is to use plugin, I got your trace but I have none of your code, I can't help you more

**Comment by AdakHaddad** [comment]
Much appreciated for the instant reply , Ok ive already push it.

**Comment by jr-k** [comment]
Here is a new version with a "Dashboard sample" plugin located in the "user" directory (https://github.com/jr-k/obscreen/releases/tag/v2.2.0).

Using plugins is preferable if you want to receive updates without dealing with git merge conflicts, especially if you modify core files differently than I do from now on.

**Comment by AdakHaddad** [comment]
🙏Thank you so much, excited to contribute more with that 🚀🚀.

**Comment by jr-k** [comment]
@AdakHaddad  don't forget to star this repo if you liked it ;)
