### ISSUE TITLE
[BUG] Videos Gets Stuck and Doesn't Play

### ISSUE THREAD

**Issue by tzehuai** [jr-k/obscreen#123]
First of all, I would like to thank you for this project. It is all I need: easy-to-use, simple to install, intuitive and just works.

But I'm having some issues on videos getting stuck.

**Describe the bug**
I tried putting videos on the playlist and play it. It will play on the first time, but after it's ended, it has problem looping, and it gets stuck. If I refresh, sometimes it might play, but most of the time it will just get stuck on the beginning of the video and doesn't play.

This is the only video on the playlist:
![image](https://github.com/user-attachments/assets/bd560004-5d94-4c50-b92b-3b31b93e6de3)

**To Reproduce**
1. Upload video in Content
2. Add video into a playlist
3. Access the playlist via the Playlist URL
4. Play until it ends
5. Check error
6. If not happening, refresh and try again.

**Expected behavior**
The video should loop and continue to play. If refresh, it should not get stuck.

**Screenshots**
These are the logs I found:
![image](https://github.com/user-attachments/assets/54a5101a-cc4b-44d1-bb0d-278733f5a137)

Here's a video to reproduce the issue:
https://github.com/user-attachments/assets/75fa0c70-1fb6-465d-b93f-de5f198dd926

**Hardware (please complete the following information):**
 - *Device*: `VM in a PowerEdge Server`
 - *OS*: `Linux-6.8.0-39-generic-x86_64-with`
 - *Architecture*: `Intel`

**Sofware (please complete the following information):**
 - *Obscreen version*: `v2.2.1`
 - *Installation method*: `Docker`
 - *Browser*: `Chrome`
 - *Player method*: `Manually via Playlist URL`

**Additional context**

**Extra (Recommended)**
Data Backup:
[data.zip](https://github.com/user-attachments/files/16451161/data.zip)
(I couldn't upload tar file, I'm putting it as zip instead)

**Comment by jr-k** [comment]
I don't see any problem in your video. You have 1 video in your playlist (with video's duration). When you launch preview url, video seems to play well. 
Logs are ok, these lines are just "INFO" level.

**Comment by tzehuai** [comment]
@jr-k yes it can play the first time. But shouldn't it restart/loop when the video finishes? 

In addition, in the video, when I refresh the page, the video doesn't start as well.

**Comment by jr-k** [comment]
For the restart/loop issue, you're correct; the main problem was that the playlist only had one slide. Here is a fix: [GitHub Release v2.2.2](https://github.com/jr-k/obscreen/releases/tag/v2.2.2).

If videos aren't starting in your computer browser, check this guide: [Why Aren't Videos Playing?](https://github.com/jr-k/obscreen?tab=readme-ov-file#videos-arent-playing-why-)
