### ISSUE TITLE
Unable to upload big files 

### ISSUE THREAD

**Issue by Adogan75** [jr-k/obscreen#13]
After setting up the system (without reserve nginx proxy) I am not able to upload big files. A video with 11mb was ok, a video with 18 mb gave an error (max file size)

How can fix that? Which file needs to be changed,  command to be fix that?

Is it Webserver.py
class WebServer:

    MAX_UPLOADS = 16 * 1024 * 1024

the right settings for this?

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.7
