### ISSUE TITLE
Duration Takes Negative Values

### ISSUE THREAD

**Issue by goknurderinoz** [jr-k/obscreen#132]
When I click the Add Slide button, the Duration setting appears in the window. When I click the down arrow in the Duration section, I see negative values. I think a validation can be added so that the negative values ​​do not appear.

**Comment by goknurderinoz** [comment]
Added min="0" parameter : 

<input type="number" name="duration" id="{{ tclass }}-duration" required="required" value="3" min="0" />

**Comment by goknurderinoz** [comment]
Added min="0" parameter : <input type="number" name="duration" id="{{ tclass }}-duration" required="required" value="3" min="0" />

**Comment by goknurderinoz** [comment]
Added new parameter add.jinja.html min="0"

**Comment by jr-k** [comment]
thanks @goknurderinoz the patch will be available in next release
