### ISSUE TITLE
[BUG] Playlist Disable Functionality Not Working

### ISSUE THREAD

**Issue by mayronsergio** [jr-k/obscreen#135]
**Describe the bug**
I tried disabling a playlist, but when I access its URL, the content continues to appear normally. The playlist should be disabled and not accessible.

See that the playlist is disabled:
![image](https://github.com/user-attachments/assets/bd47aed2-311c-4847-ab26-1fbfd921aab2)

See that even though it's disabled, it continues to work:
![image](https://github.com/user-attachments/assets/4490438e-526e-4ceb-8f1a-20fbccc9285b)

**To Reproduce**
1. Select a Playlist
2. Click on 'Enable/Disable playlist'
3. Access the playlist via the Playlist URL
4. Check error

**Expected behavior**
The playlist should not be functioning and should be disabled.

**Hardware (please complete the following information):**
 - *Device*: `Computer with Intel Core i7 processor`
 - *OS*: `Windows 10 with WSL 2 (Windows Subsystem for Linux 2)` 
 - *Architecture*: `x86_64` [use command *uname -a*]

**Sofware (please complete the following information):**
 - *Obscreen version*: `v2.4.0`
 - *Installation method*: `Docker`
 - *Browser*: `Chrome`
 - *Player method*: `Manually via Playlist URL`

**Additional context**
This bug can also be reproduced on demo.obscreen.io

**Comment by jr-k** [comment]
@mayronsergio is it better with https://github.com/jr-k/obscreen/releases/tag/v2.4.1 ?
