### ISSUE TITLE
Uncaught TypeError: slide.innerHTML.replaceAll is not a function

### ISSUE THREAD

**Issue by tzehuai** [jr-k/obscreen#138]
**Describe the bug**
People using slightly older browsers are getting the error:
`Uncaught TypeError: slide.innerHTML.replaceAll is not a function`

![image](https://github.com/user-attachments/assets/6305c3e5-d96e-4c5c-9ebb-c99ed6bbb582)

It seems like the `.replaceAll` function could be rather new based on what I found (e.g. https://stackoverflow.com/a/67877325)

Correct me if I'm wrong, it could be coming from here. Is it possible to change the usage of it to maybe `.replace` to support older browsers?

https://github.com/jr-k/obscreen/blob/63de70611d2842aa1ae7dbda3c194a6e1600f842/views/player/player.jinja.html#L196

**To Reproduce**

**Expected behavior**
To play the slides without the error.

**Screenshots**

**Hardware (please complete the following information):**
 - *Device*: `VM`
 - *OS*: `Linux-6.8.0-39-generic-x86_64-with` 
 - *Architecture*: `Intel`

**Sofware (please complete the following information):**
 - *Obscreen version*: `v2.3.0`
 - *Installation method*: `Docker`
 - *Browser*: `Chromium` or `Chrome`
 - *Player method*: `Systemd with obscreen-player.service`

**Additional context**

**Extra (Recommended)**
You can send us a backup of your data to help speed up the debugging process. Please ensure that no sensitive data is included in your slides and follow these steps:
N/A

**Comment by jr-k** [comment]
Thanks for your feedback. This is now fixed in https://github.com/jr-k/obscreen/releases/tag/v2.4.2
