### ISSUE TITLE
[FEATURE] Obscreen Update/Forcing Screen Resolution

### ISSUE THREAD

**Issue by ryanmilla** [jr-k/obscreen#143]
**Is your feature request related to a problem? Please describe.**
Not a problem, but nice to have. Ignore if you already have these features. I was wondering if it's easy to update Obscreen & if it's possible to force 1920x1080 screen resolution on a 4k TV (either on the Obscreen console or CLI) 

**Describe the solution you'd like**
Update Obscreen with newest features/force TV resolution based on user needs (either on Obscreen GUI or CLI)

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by jr-k** [comment]
@ryanmilla for now, there is no server logic in players, just an autorun script for the X server (GUI) and Chromium browser.
While I'm working on something more automated, you can add this to line 13 of the var/run/play file:

```bash
FIRST_CONNECTED_SCREEN=$(xrandr | grep " connected" | awk '{print $1}' | head -n 1)
xrandr --output $FIRST_CONNECTED_SCREEN --mode 1920x1080
```
