### ISSUE TITLE
How to set up an environment on my own machine to test and run the webpage

### ISSUE THREAD

**Issue by Taihoa52** [jr-k/obscreen#146]
After running the source code on my local machine, I found that I couldn't access the demo webpage properly. After investigating various situations, I don't know what the reason is. How did the author compile the file.
I have these errors, but I have installed the corresponding dependencies, but they still occur during runtime.
![Snipaste_2024-08-24_18-23-27](https://github.com/user-attachments/assets/6a3de5c9-232b-4773-8fe5-833d234298f0)

**Comment by jr-k** [comment]
Open a shell in obscreen-master directory and execute:
```bash
source venv/bin/activate
pip install -r requirements.txt
```
Copy-paste all output here.

**Comment by jr-k** [comment]
You are on Windows. Follow installation script for Windows then. (The question has been answered on Discord ✅)
