### ISSUE TITLE
Output via script

### ISSUE THREAD

**Issue by GrLinkDn** [jr-k/obscreen#149]
I saw the new compose feature which I personally think is awesome.

I came up with a use case when looking at this feature that I think is interesting.

The possibility of outputting values ​​obtained via script.

For example a countdown or a counter relating to a ticket or similar.

Using a script you could obtain/calculate the desired value or string and then insert it on the screen.

A note that has nothing to do with this function.

I used your addition with chromecast and it works correctly!

**Comment by jr-k** [comment]
Yes, it's planned. Scripts and RSS feed data injection :)
