### ISSUE TITLE
Studio - Not all settings visible

### ISSUE THREAD

**Issue by swobx-msv** [jr-k/obscreen#158]
**Describe the bug**
Obscreen was installed according to the instructions.
I then wanted to adjust the settings to activate Fleet screen management and Authentication management. However, these two points are not displayed. 
Unfortunately, I couldn't find anything about this in the documentation.

**Screenshots**
<img width="1679" alt="Bildschirmfoto 2024-09-16 um 21 05 38" src="https://github.com/user-attachments/assets/e28a5e6d-fd62-4996-abf0-ad7445215da1">

**Hardware (please complete the following information):**
 - *Device*: `Raspberry Pi 4 Model B Rev`
 - *OS*: `Raspbian v12`
 - *Architecture*: `arm64`

**Sofware (please complete the following information):**
 - *Obscreen version*: `v2.7.0`
 - *Installation method*: `System`
 - *Browser*: `Chromium`
 - *Player method*: `Systemd with obscreen-player.service`

thank you for your help!

**Comment by Rom0067** [comment]
Same issues. I posted yesterday about changing ports and then later added this issue to the post.

**Comment by ecm75** [comment]
Same issue here with both docker and native install from current git master branch.
OS: Ubuntu 22.04
Arch: amd64
