### ISSUE TITLE
[Feature request] Self contained Docker image

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#17]
Currently the Docker image itself is not enough to spin up the container. One must also clone the git repo in order to pull in the necessary assets, which are mounted on /app to the container. Without these assets, the container will not start.

Ideally an Docker image can be run standalone. This would also simplify updating, as only the Docker image would have to be (re)pulled instead of both the git repo and Docker image. As such it would be nice to have a self contained Docker image.

Thank you for considering.

**Comment by jr-k** [comment]
What about now ?
