### ISSUE TITLE
[FEATURE] Add the possbility to add grafana dashboards usign the grafana service accounts

### ISSUE THREAD

**Issue by gordnhoo** [jr-k/obscreen#2]
**Describe the solution you'd like**
Here is the feature i would like to have this company already uses it and would need the same for zabbix
https://www.screenly.io/tutorials/grafana/

**Additional context**
We have been testing your product and we enjoy it a lot and were thinking of buying it but this is a feature we would very much appreciate.

**Comment by jr-k** [comment]
On what raspberry pi exactly please?

**Comment by gordnhoo** [comment]
Raspberry pi 4

**Comment by gordnhoo** [comment]
**I managed to create a way to auto login into zabbix,grafana and icigna for anyone that needs it**
**FOR THIS TO WORK ON OBSCREEN HTTPS MUST BE ENABLED**
**Under /obscreen/var/run/ext/  Create the javscript logins for your needs here is an example of icinga**
**add this script under icinga.js** 
```
document.querySelector('input[name="username"][placeholder="Username"]').value = 'YOUR_USERNAME_HERE';
document.querySelector('input[name="password"][placeholder="Password"]').value = "YOUR_PASSWORD_HERE";
document.querySelector('input[type="submit"][value="Login"]').click();
```
**Under manifest.json do the following**
```
{
  "manifest_version": 3,
  "name": "Disable CSP and X-Frame-Options",
  "version": "1.0",
  "permissions": [
    "declarativeNetRequest",
    "declarativeNetRequestWithHostAccess",
    "tabs",
    "activeTab",
    "webRequest",
    "webRequestBlocking",
    "scripting"
  ],
  "host_permissions": [
    "*://*/*"
  ],
  "background": {
    "service_worker": "background.js"
  },
  "declarative_net_request": {
    "rule_resources": [
      {
        "id": "ruleset_1",
        "enabled": true,
        "path": "rules.json"
      }
    ]
  },
  "content_scripts": [
    {
      "matches": ["https://grafana/*"],
      "js": ["graf.js"],
      "all_frames": true
    },{

      "matches": ["https://zabbix/*"],
      "js": ["zab.js"],
      "all_frames": true
    },{

      "matches": ["https://icinga/*"],
      "js": ["icinga.js"],
      "all_frames": true
    }
  ]
}
```

**Comment by jr-k** [comment]
These cases will be manageable through new Obscreen Player OS very soon. But thanks for this solution !
