### ISSUE TITLE
[Feature Request] Schedule Slides

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#2]
It would be great if we could schedule slides, for example to run a temporary promotion. Similar to the scheduling feature in Anthias or Screenly.

Thank you

**Comment by jr-k** [comment]
[I don't know this feature, can you tell me more about it ? You mean, schedule a slide at a specific moment in time ? Then it never appear agai](https://github.com/jr-k/obscreen/releases/tag/v1.6)

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.6

**Comment by Freekers** [comment]
Thank you very much! I'll play around with it :)
