### ISSUE TITLE
[BUG] Issues running the obscreen service

### ISSUE THREAD

**Issue by gordnhoo** [jr-k/obscreen#3]
**Describe the bug**
When running the installation script for the player and doing a reboot the x server doesn't lunch and breaks every time as an alternative i followed this tutorial which made everything work.
https://www.alessandroscola.com/en/computers/build-a-kiosk-with-raspberry

**To Reproduce**
1.run the script curl -fsSL https://raw.githubusercontent.com/obscreen/obscreen/master/system/client/install-client-player.sh -o /tmp/install-client-player.sh && chmod +x /tmp/install-client-player.sh && sudo /bin/bash /tmp/install-client-player.sh $USER $HOME
2. reboot

**Expected behavior**
The screen should immediately start with obscreen

**Comment by jr-k** [comment]
Manual installation will be deprecated with new Obscreen Player OS coming very soon. Let's chat on discord about this (I need beta testers 😀)
