### ISSUE TITLE
[Bug] English translation is missing for 'Options du lecteur' in General Settings

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#36]
In General Settings, the English translation for 'Options du lecteur' is missing:

![afbeelding](https://github.com/jr-k/obscreen/assets/1370857/4047bf60-941a-4d3a-8673-6be75f5e89bd)

Thank you

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.11 

(I've decided to replace version 1.11 with a fixed one, tell me if it's working now)
