### ISSUE TITLE
[Feature request] Enhance user experience for 'Slide upload limit' settings

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#37]
Thanks for implementing the Slide upload limit setting, I appreciate it.
It enhance the user experience if we could just enter the limit in MB instead of having to do the calculations by hand.

Thanks for considering

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.11 

(I've decided to replace version 1.11 with a fixed one, tell me if it's working now)

**Comment by Freekers** [comment]
The docker image has not been updated (yet), so I cannot test the changes.

**Comment by jr-k** [comment]
Sorry my bad, it's building...
