### ISSUE TITLE
error on RPI 3b+

### ISSUE THREAD

**Issue by Yakouao** [jr-k/obscreen#38]
Hi,

Thanks for this good project.

I can install it on a synology nas without error but when i try it on fresh RPI 3 B+ (fresh raspian lite 64 bit), i've got this error that i don't understand : 

[+] Running 10/10
 ✔ webapp Pulled                                                         113.6s
   ✔ b82e4fd40279 Pull complete                                            2.7s
   ✔ 7b3473a9ea4b Pull complete                                            7.1s
   ✔ ac0d21afccfb Pull complete                                           11.8s
   ✔ 3b6efca90320 Pull complete                                           11.9s
   ✔ 433a8c8f300a Pull complete                                           15.8s
   ✔ 5c650cbadc7e Pull complete                                          106.2s
   ✔ 876f6b922a3d Pull complete                                          106.4s
   ✔ 1b12ec1cefca Pull complete                                          107.0s
   ✔ 94aaf734aaaa Pull complete                                          111.4s
[+] Running 2/2
 ✔ Network obscreen_default  Created                                       0.3s
 ✔ Container obscreen        Created                                       0.8s
Attaching to obscreen
obscreen  | Traceback (most recent call last):
obscreen  |   File "/app/obscreen.py", line 7, in <module>
obscreen  |     app = Application(project_dir=os.path.dirname(__file__))
obscreen  |   File "/app/src/Application.py", line 18, in __init__
obscreen  |     self._model_store = ModelStore()
obscreen  |   File "/app/src/service/ModelStore.py", line 23, in __init__
obscreen  |     self._config_manager = ConfigManager(variable_manager=self._vari                able_manager)
obscreen  |   File "/app/src/manager/ConfigManager.py", line 37, in __init__
obscreen  |     self.autoconfigure()
obscreen  |   File "/app/src/manager/ConfigManager.py", line 97, in autoconfigur                e
obscreen  |     self.autoconfigure_lxconf()
obscreen  |   File "/app/src/manager/ConfigManager.py", line 122, in autoconfigu                re_lxconf
obscreen  |     with open(destination_path, 'w') as file:
obscreen  | IsADirectoryError: [Errno 21] Is a directory: '/app/var/run/lxfile'
obscreen exited with code 0

Thanks

**Comment by jr-k** [comment]
Can you post the content of your .env file ? Thanks

**Comment by Yakouao** [comment]
Where is this file ?

I try to run the image with these command : 

# Prepare application data file tree
mkdir -p obscreen/data/db obscreen/data/uploads && cd obscreen

# Run the Docker container
# If you ARE NOT on a RaspberryPi ignore the line (-v /home/pi/....)
docker run --rm --name obscreen --pull=always \
  -e DEBUG=false \
  -e PORT=5000 \
  -e AUTOCONFIGURE_LX_FILE=/app/var/run/lxfile \
  -e SECRET_KEY=ANY_SECRET_KEY_HERE \
  -p 5000:5000 \
  -v ./data/db:/app/data/db \
  -v ./data/uploads:/app/data/uploads \
  -v /home/pi/.config/lxsession/LXDE-pi/autostart:/app/var/run/lxfile \
  jierka/obscreen:latest

**Comment by jr-k** [comment]
Ok I think I know, before docker run, execute this command with your `pi` user: `touch /home/pi/.config/lxsession/LXDE-pi/autostart`

**Comment by Yakouao** [comment]
Yes, thanks a lot. 
Now i can run the image. 
Perhaps you could add in the readme the command line to add the autostart file...

How to use the authentication, i follow your step in https://github.com/jr-k/obscreen/issues/4#issuecomment-2104239081 but i have no user menu ?

I'm going to try with docker compose

Also, as there is a start date for the slide, could you add a end date if needed ? 

Thanks again

**Comment by jr-k** [comment]
Version 1.12 (https://github.com/jr-k/obscreen/releases/tag/v1.12) adds some additional logs and more documentation around this topic. I hope it'll help in the future.

For authentication I'm posting a patch right now

For end date, alright, I think I'll work on this in the next days.

Thanks for the feedback

**Comment by jr-k** [comment]
Updated v1.12 version (https://github.com/jr-k/obscreen/releases/tag/v1.12)

**Comment by Yakouao** [comment]
Thanks, i tried it and actually when i activate authentication it give me an error 500

**Comment by Freekers** [comment]
> Thanks, i tried it and actually when i activate authentication it give me an error 500

I have the same issue. I have opened a new issue with logs here: https://github.com/jr-k/obscreen/issues/45

**Comment by jr-k** [comment]
Sorry for the back and forth, I've found the issue, the way I'm testing the application while developing isn't close enough to production run, I'll replace release v1.12 in next hour

**Comment by jr-k** [comment]
@Yakouao  Can you test this new v1.12 please ? :) Thanks 🙏

**Comment by Yakouao** [comment]
yes now the user menu appear as intended... 👍 

so i made a new user and then when i try to logout unfortunatly new 500 error appear...

Also, i tried the youtube url but not seems to work... Which is the correct url to insert : 

- https://www.youtube.com/watch?v=xxxxx&list=xxxxxx&start_radio=1
- or
- https://youtu.be/xxxxx?si=s1_xxxxxxx

Thanks

**Comment by jr-k** [comment]
Ok, I'll fix logout.

For youtube, safe working URL are like this one: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by jr-k** [comment]
@Yakouao Here we go with cursed version 1.12 🥲, please give it a try and bring me some good news 👍
Thanks
