### ISSUE TITLE
[Feature Request] Authentication for admin panel / back-end

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#4]
Currently the admin panel / back-end is not secured and accessible by anyone who knows the URL. It would be nice if we could secure it using some credentials, for example using basic authentication.

Thanks

**Comment by jr-k** [comment]
I think it's a better approach to use [nginx basic authentication ](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/), wdyt ?

**Comment by Freekers** [comment]
Yes, agreed, that would be nice :)

**Comment by jr-k** [comment]
You misunderstood my point, I was pointing out that implementing an authentication for this project is useless if you use nginx as a basic auth guard thanks to htpasswd directive in nginx.

Nevermind, I think it may be useful if I add some right management inside obscreen soon enough, until then, here is a basic auth/login module :)
https://github.com/jr-k/obscreen/releases/tag/v1.11

**Comment by Freekers** [comment]
Sorry, my bad. I do appreciate the basic auth/login module. I just tried it, but I'm a bit puzzled on how to setup a user.
In the docker-compose file, I've specified a ```SECRET_KEY````.  I assumed this is the password for the login screen.
However, after enabling the user management module and restarting the container, I'm prompted with a username/password login screen. Where do I find/set the username? I tried to left it blank but it doesn't accept it.

**Comment by jr-k** [comment]
1. Run application (set a random secret_key)
2. Go to settings and enable authentication
3. Do not restart, a new page "users" will appear in the menu, add your user there
4. Restart and use your newly created user

**Comment by jr-k** [comment]
Working on a patch

**Comment by jr-k** [comment]
Sorry there was an issue, here is a patched version https://github.com/jr-k/obscreen/releases/tag/v1.12
