### ISSUE TITLE
[FEATURE] Overlay Logo

### ISSUE THREAD

**Issue by gipainformatica1** [jr-k/obscreen#4]
Being able to overlay a logo like a "News Channel", something like "MTV" (Logo). This will help to have identity of the channel and more "professional" look.

Avoid re-editing of many already produced films (many without sources anymore)

Features: 

1) placement (we may choose one of the 4x corners of the screen)

2) Size: Up to x/y megapixels size

3) Transparency: being able to choose transparency level

4) Change logo according to playlist (1 x logo/ Playlist )

All these 4x features could be customized within the playlist

Thank you ! 

I believe we have a winner here if this feature it's implemented.

**Comment by jr-k** [comment]
Coming soon
<img src="https://media.cleanshot.cloud/media/97152/GhWBN9T9tmPL5HRPhjA8pCqgyUTfsidnbhOc3qz5.jpeg?Expires=1734664382&Signature=YIKDDD4U8VyOv9PlejjEwHpbL7HBJny7dLkUZLk6psaYCACFD7au-O~73~4-kmNwt0LCq4T5RxEM-Ty8tpkWxQw~GQovFReR3rG-nOg~Ozu4kgOmb-MOSlCouFIAYDE23IK65Wn65dSe1ZLa4NxH48IrRcxwaGEnDih7zdFTgi90KmfFQMDAHYgipM5Kx82UYf7bhxkTX1LxqCmoWjI0WRl31zBDuUYi5bMSoYFGikNhQ99P1Dr6g3MzxszpvU92lydHJLj3cW6qJT1aE3NCIQowrkYlJxMoUgtXiuvZYV4OCrlWZpec-UyiVYUlkBCzHCUX2lMlvV2rOsYe3CeKow__&Key-Pair-Id=K269JMAT9ZF4GZ" />

**Comment by jr-k** [comment]
@gipainformatica1 Available on [2024.12.1](https://github.com/obscreen/obscreen/releases/tag/2024.12.1)
