### ISSUE TITLE
[Feature Request] Device management, groups, and shared slides across screens.

### ISSUE THREAD

**Issue by adamgranted** [jr-k/obscreen#55]
Hello! I love the simplicity of Obscreen. I am wishing it had the ability to do two additional things both of which pertain to device management. The inspiration comes from both Xibo and the now deprecated DisplayKiosk project.

While Fleet View is helpful, it's still essentially individual management of devices - one at a time. You have to go to each device manually to update the slides. It would be awesome to see a master/slave relationship where a single unit is designated as the master, it manages the slave displays, and from the master you can assign slides to groups of devices or individual devices.

For example:

- Master is running locally on a docker container. This server is headless and has no physical display.
- 4x Raspberry Pis are running 4 separate displays mounted on a wall. 2 of the displays need to show the same thing and the remaining two show something unique.
- You add each of the raspberry pi devices as a new screen via the "Master" portal
- From the master you can create a new device group ("Group A") and add the 2x raspberry pi slave screens to it.
- From the master you can create the playlist then apply it to the device group "Group A"
- From the master you can create two more unique playlists then apply them directly to the remaining two devices.
 
Our particular use case is to manage many devices displaying BI dashboards across multiple locations. Each device will be within a VPN so they can communicate across the individual WANs.

Thanks for the consideration!

**Comment by jr-k** [comment]
UX is not perfect and you'll need some clics to achieve your goal but here is a first try https://github.com/jr-k/obscreen/releases/tag/v1.19

**Comment by adamgranted** [comment]
Thank you! I'll get all the devices updated and give it a try later this week
