### ISSUE TITLE
[Feature Request] manage and setting page enhancement

### ISSUE THREAD

**Issue by Yakouao** [jr-k/obscreen#60]
1. Add a button previous slide and one for next slide in the manage page
2. make the setting page more verbose : rpi model info, free space, memory usage, mac address, os version, the last xx line of logs,...
3. add a button to update obscreen to the last version ?

Thanks 👍

**Comment by jr-k** [comment]
1. Need to add some studio to player websocket communication. Heavy development for minor change.
2. Yeah it's on track
3. I've added some explanations in readme.md to upgrade. For docker, it's not a good choice I think. For system wide installation, why not.

**Comment by Yakouao** [comment]
1. yes for sure. As you say it is minor change
2. 👍 
3. For wide system are these commands pulling the git ?

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.17 for git updater plugin
