### ISSUE TITLE
Power failure

### ISSUE THREAD

**Issue by Yakouao** [jr-k/obscreen#61]
Install on RPI4 with other user than pi without any error 👍 

In case of power failure, on reboot the service obscreen-manager.service won't start again : 
`● obscreen-manager.service - Obscreen Manager
     Loaded: loaded (/etc/systemd/system/obscreen-manager.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2024-05-17 17:01:32 CEST; 3s ago
    Process: 6968 ExecStart=/home/yakouao/obscreen/venv/bin/python /home/yakouao/obscreen/obscreen.py (code=exited, status=1/FAILURE)
    Process: 6969 ExecStartPost=/usr/bin/sudo /bin/bash -c sudo systemctl restart obscreen-player.service 2>/dev/null || true (code=exited, status=0/SUCCESS)
   Main PID: 6968 (code=exited, status=1/FAILURE)
        CPU: 819ms
`
Is there a way to prevent it ?

Thanks you

**Comment by jr-k** [comment]
I tried with my raspberry (with a user other than pi). Unplug cable while running then reboot and It's starting after booting up. Sorry but if I can't reproduce this, I can't fix anything.

**Comment by Yakouao** [comment]
Do you try in docker or wide install ?

I've tried two times in wide install and got same error on booting.

I'm going to try another time.

Thanks you

**Comment by jr-k** [comment]
Wide install

**Comment by jr-k** [comment]
try that: `cd ~/obscreen rm data/db/slideshow.json && cp data/db/slideshow.json.dist data/db/slideshow.json`

**Comment by jr-k** [comment]
I think I've found the issue, sometimes, if the app is killed brutally, file data/db/slideshow.json is being flushed.

**Comment by Yakouao** [comment]
Yes i understand 👍

**Comment by jr-k** [comment]
@Yakouao https://github.com/jr-k/obscreen/releases/tag/v1.15 is it better with this change ?

**Comment by Yakouao** [comment]
Unfortunately the update didn't work.

So i made a fresh install and this is the error during installation (when launching python requirements : 

`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/python-dotenv/`
`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/click/`
`DEPRECATION: pysqlite3 is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`

And after `python ./obscreen.py` : 
`sqlite3.OperationalError: unable to open database file`

Thanks

**Comment by jr-k** [comment]
@Yakouao execute `cd ~/obscreen && mkdir data/db`, i'm gonna fix this, just a .gitkeep to add
