### ISSUE TITLE
Black screen after a long period

### ISSUE THREAD

**Issue by Yakouao** [jr-k/obscreen#66]
Hi,

Installation v1.15 wide system on rpi4b.
I've noticed that after about 2 or 3 hours the slideshow won't show anymore. Instead there is a black/grey  screen. nor the mouse or the keyboard wake the slideshow, you have to manually restart it.

I tried several times and have the same result.

I tried to add `consoleblank=0`  to this file `/boot/firmware/cmdline.txt` with no effect...

I'm going to try with another screen in case...

Thanks

**Comment by jr-k** [comment]
This one will be hard to troubleshoot if I need to wait 2,3 hours every time 🥲

**Comment by Yakouao** [comment]
So the test with another screen is with same result... Black screen after about 5 hours ....

I'm going to try with xscreensaver...

**Comment by jr-k** [comment]
This line matters: https://github.com/jr-k/obscreen/blob/feature/playlists/src/manager/ConfigManager.py#L134

**Comment by Yakouao** [comment]
ok thanks 👍 

In wide system, to make the update is these commands correct ? : 

`cd ~/obscreen && git pull`
`sudo systemctl restart obscreen-manager.service`

**Comment by Yakouao** [comment]
No need to wait to much.
I ad `xscreensaver -no-splash` in ConfigManager.py 
then reboot and the slideshow don't run :( only black screen

**Comment by Yakouao** [comment]
Here are the logs : 
`self._db.update_by_id(self.TABLE_NAME, raw_slide['id'], user_tracker_edits)`
`File "/home/pi/obscreen/src/manager/DatabaseManager.py", line 128, in update_by_id`
`return self.update_by_query(table_name, "id = {}".format(id), values)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "/home/pi/obscreen/src/manager/DatabaseManager.py", line 118, in update_by_query`
`return self.execute_write_query(`
`^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "/home/pi/obscreen/src/manager/DatabaseManager.py", line 64, in execute_write_query`
`with self._conn:`
`SystemError: error return without exception set`

Thanks

**Comment by jr-k** [comment]
I'm actually testing (without xscreensaver) and it's been 5 hours:
```bash
~ $ uptime
 23:41:20 up  5:03,  1 user,  load average: 0.15, 0.10, 0.11
```

No black screen

**Comment by Yakouao** [comment]
My bad... :( i think it was an error du to the update of the kernel that seems to be unstable...
