### ISSUE TITLE
date stop scheduler

### ISSUE THREAD

**Issue by Yakouao** [jr-k/obscreen#68]
Thanks for the date stop.

However if you add a date stop the duration disappear and the slide won't show anymore

In the Schedule Overview page there is only the start  date and not the stop date

Also before v1.16, i've noticed that what duration you entered for a video file, the video played until the end and not in the v1.16, am i wrong ?

Many thanks

**Comment by jr-k** [comment]
1. Yeah, a slide has a start date and an end date. The end can be a duration or a specific point in time.
2. Yup, that's a missing feature. A global UI rework is coming, but I'll add this one soon.
3. Yes, with time sync it becomes problematic to rely on the video file's duration (if some players have buffering delays, the playlist becomes out of sync; a fixed and strict duration solves this issue). A warning shows in the console to indicate a duration mismatch between the onscreen time and the video's duration.

**Comment by Yakouao** [comment]
>Yeah, a slide has a start date and an end date. The end can be a duration OR a specific point in time, not both.

yes i understand but the problem is that the slide with a stop date (a video in my case) is not diplaying at all

**Comment by jr-k** [comment]
What player are you using ? Chromium on rpi ?

**Comment by Yakouao** [comment]
Yes rpi4 in wide system with chromium

**Comment by jr-k** [comment]
I've pushed a small fixe, can you test pls ? Thanks

**Comment by Yakouao** [comment]
I'm going to test it again as the first try was bad
Yes it is a good idea. I'm not social network friendly but it could be by mail, signal, whatstsap or telegram or if you have a better idea ;)

**Comment by jr-k** [comment]
Alright. What about discord ?

**Comment by Yakouao** [comment]
yes why not 👍

**Comment by jr-k** [comment]
https://discord.obscreen.io/
