### ISSUE TITLE
[Feature Request] add auto video duration option

### ISSUE THREAD

**Issue by Yakouaho** [jr-k/obscreen#76]
If possible, add a button to play the entire video rather than the duration in seconds ?

**Comment by jr-k** [comment]
be aware: this will obviously not work with time synced playlist, alright ?

**Comment by Yakouaho** [comment]
Yes, that's allright for some use case

Thanks

**Comment by ShubhamGhait** [comment]
Could you guide for as  in my case audio is not working  and some of the video also not play?
could you specified in  audio and video supported format?

**Comment by jr-k** [comment]
@ShubhamGhait for audio you can
1. `sudo apt install -y pulseaudio`
2.`sudo reboot
3. `sudo raspi-config nonint do_audio 1`

Tell me if it's better. Next time, open a new issue.

**Comment by jr-k** [comment]
@Yakouaho Sorry for the delay, but there it is: https://github.com/jr-k/obscreen/releases/tag/v2.1.0
