### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Yakouaho** [jr-k/obscreen#78]
Hi,

Thank you for this new big release 👍 

However, in wide system with fresh installation i've got the error : `Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

The logs : 
`   File "/home/pi/obscreen/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
     rv = self.dispatch_request()
          ^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/pi/obscreen/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/pi/obscreen/src/controller/PlayerController.py", line 54, in player
     if node_player.group_id:
        ^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'group_id'`

Thx

**Comment by jr-k** [comment]
Can you try again with today's update please ? Thanks

**Comment by Yakouaho** [comment]
Yes, it's ok now.

Thanks you ;)
