### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by AlexPjz** [jr-k/obscreen#83]
Hi! I tried to join the discord server but the link has expired. Is there a way to show the displays on android screen TV?

**Comment by jr-k** [comment]
What browser on your TV ?

I've updated discord link and set no expiration, thanks.

**Comment by AlexPjz** [comment]
What browsers are compatible? I have not purchased the tv yet.

**Comment by jr-k** [comment]
I can't test all tvs on the market so it's impossible for me to answer that question. If you want to display anything except video, I'm pretty sure it'll do the job pretty easily on any tv. For videos, you'll need to test before you buy.
