### ISSUE TITLE
video with start and end date pause at the end of the video

### ISSUE THREAD

**Issue by Yakouaho** [jr-k/obscreen#85]
Hi jrk,

This time the video is playing but stay in "pause" at the end of the video... (on the last image of the video)

_Originally posted by @Yakouaho in https://github.com/jr-k/obscreen/issues/75#issuecomment-2182815069_

**Comment by jr-k** [comment]
Yes I think it's normal. Why do you have a end date and not a duration ? You need a video endless loop until end date ?

**Comment by Yakouaho** [comment]
i think it's misunderstanding.

For me , i'd like a slide to be shown from an start date and not shown (desactivate the slide) at the stop date... like a scheduler (show the slide beetween 2 date)

Hope you'll understand what i mean :)

**Comment by jr-k** [comment]
An update may address your issue: https://github.com/jr-k/obscreen/releases/tag/v1.20.0
