### ISSUE TITLE
[FEATURE] Bundle jQuery with the install

### ISSUE THREAD

**Issue by kverqus** [jr-k/obscreen#86]
**Is your feature request related to a problem? Please describe.**
Running Obscreen in a network without internet connection requires additional tweaking of the software due to jQuery not being bundled with the Obscreen installation. While possible to manually add this to the system wide installation, it's a lot more cumbersome for the Docker alternative.

**Describe the solution you'd like**
Include jQuery in the project. I'm not sure if such a solution would introduce a licensing issue.

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.19.4
